Set1 = set('abcdefg')   
print(Set1)
print(type(Set1))
Set1.add('String1')  
print(Set1)
Set1.add(7)       
print(Set1)
Set1.add(6)            
print(Set1)
Set1.add(3.5)           
print(Set1)
Set1.add(True)        
print(Set1)
Set1.add(False)       
print(Set1)
